// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjEIfaGB4jga-YrDco95vgdLXbvx70m64',
    appId: '1:85010899908:web:823816b93f82718f5bba91',
    messagingSenderId: '85010899908',
    projectId: 'artographia-fyp',
    authDomain: 'artographia-fyp.firebaseapp.com',
    storageBucket: 'artographia-fyp.appspot.com',
    measurementId: 'G-23D46ZFK1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-9FiaDba7JiEy0uUGxJyYXTsLu3s3QMk',
    appId: '1:85010899908:android:13605be51796a2b35bba91',
    messagingSenderId: '85010899908',
    projectId: 'artographia-fyp',
    storageBucket: 'artographia-fyp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpUr0E4K9I0K0zST9sY7fpo8YVlfbIgPc',
    appId: '1:85010899908:ios:40bb0b05d1cf29ca5bba91',
    messagingSenderId: '85010899908',
    projectId: 'artographia-fyp',
    storageBucket: 'artographia-fyp.appspot.com',
    iosBundleId: 'com.example.artographia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpUr0E4K9I0K0zST9sY7fpo8YVlfbIgPc',
    appId: '1:85010899908:ios:b5e59ff5a269ed465bba91',
    messagingSenderId: '85010899908',
    projectId: 'artographia-fyp',
    storageBucket: 'artographia-fyp.appspot.com',
    iosBundleId: 'com.example.artographia.RunnerTests',
  );
}
