name: Flutter CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # 4. Navigate to the directory containing main.dart
      - name: Navigate to Example Directory
        run: cd example/image_classification_mobilenet

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.1" # You can adjust the Flutter version here

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter run

      # - name: Build Android APK
      #   run: flutter build apk

      # - name: Build iOS app
      #   run: flutter build ios
      #   # Note: For iOS builds, you may need to set up additional configurations like signing.

      # - name: Archive artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: build
      #     path: |
      #       build/
